[project]
name = "ml-analytics-tools"
version = "0.0.1"
description = "Tools for ML projects and data management"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.37.24",
    "logging>=0.4.9.6",
    "mlflow>=2.21.2",
    "redshift-connector>=2.1.5",
]
